<?php

return [
    'coffee-date-corner' => [
        'slug' => 'coffee-date-corner',
        'aliases' => ['family-portrait-signature', 'family-portrait'],
        'name' => 'Coffee Date Corner',
        'category' => 'Date Night',
        'price' => 'Rp. 150.000',
        'duration' => '2 jam',
        'image' => 'assets/images/hero.jpg',
        'summary' => 'Reservasi meja hangat untuk dua orang dengan suasana yang lebih intim.',
        'description' => 'Pilihan reservasi untuk pasangan atau dua sahabat yang ingin menikmati Cafe Amiko dengan alur yang rapi, suasana tenang, dan sentuhan yang lebih personal.',
        'facilities' => [
            'Meja reservasi untuk 2 orang',
            '2 welcome drinks pilihan house menu',
            'Prioritas area indoor yang lebih nyaman',
            'Dekor meja sederhana untuk momen spesial',
        ],
        'notes' => [
            'Cocok untuk quality time sore hingga malam hari.',
            'Datang 10-15 menit lebih awal agar meja tetap aman.',
            'Bisa request area dekat jendela sesuai ketersediaan.',
        ],
    ],
    'work-brew-table' => [
        'slug' => 'work-brew-table',
        'aliases' => ['graduation-highlight', 'graduation-session'],
        'name' => 'Work & Brew Table',
        'category' => 'Work Space',
        'price' => 'Rp. 200.000',
        'duration' => '3 jam',
        'image' => 'assets/images/about.png',
        'summary' => 'Area nyaman untuk kerja, meeting kecil, atau nugas bareng.',
        'description' => 'Dirancang untuk tamu yang butuh meja stabil, akses colokan, dan suasana creative coffee space yang tetap hidup tanpa mengganggu fokus.',
        'facilities' => [
            'Meja reservasi untuk 3-4 orang',
            'Akses prioritas ke colokan dan Wi-Fi',
            '2 pilihan kopi atau non-kopi house blend',
            'Layout meja yang nyaman untuk laptop dan diskusi',
        ],
        'notes' => [
            'Paling cocok untuk kunjungan weekday atau early evening.',
            'Bisa dipakai untuk meeting kecil tanpa set up tambahan.',
            'Silakan tulis kebutuhan kursi ekstra saat reservasi.',
        ],
    ],
    'community-night-table' => [
        'slug' => 'community-night-table',
        'aliases' => ['couple-story-session', 'couple-story'],
        'name' => 'Community Night Table',
        'category' => 'Community',
        'price' => 'Rp. 350.000',
        'duration' => '3 jam',
        'image' => 'assets/images/hero.jpg',
        'summary' => 'Reservasi grup untuk komunitas kecil, board game, atau ngobrol santai.',
        'description' => 'Paket reservasi untuk rombongan yang ingin menikmati Amiko sebagai ruang nongkrong kreatif, dengan suasana hangat untuk bercakap, bermain, dan berbagi ide.',
        'facilities' => [
            'Meja reservasi untuk 4-6 orang',
            '4 minuman house beverage',
            'Area duduk yang mendukung obrolan grup',
            'Fleksibel untuk board game atau mini sharing session',
        ],
        'notes' => [
            'Ideal untuk komunitas kecil, reunian, atau catch up santai.',
            'Boleh request area yang dekat dengan panggung sesuai jadwal event.',
            'Reservasi malam lebih disarankan untuk pengalaman suasana yang penuh.',
        ],
    ],
    'live-music-hangout' => [
        'slug' => 'live-music-hangout',
        'aliases' => ['personal-branding-pro', 'personal-branding'],
        'name' => 'Live Music Hangout',
        'category' => 'Live Event',
        'price' => 'Rp. 450.000',
        'duration' => '4 jam',
        'image' => 'assets/images/about.png',
        'summary' => 'Spot terbaik untuk menikmati live music, stand-up, atau event malam.',
        'description' => 'Paket reservasi malam untuk tamu yang ingin merasakan sisi paling hidup dari Cafe Amiko: kopi, musik, dan energi komunitas dalam satu kunjungan.',
        'facilities' => [
            'Meja reservasi untuk 4-6 orang',
            '4 minuman dan 2 snack platter',
            'Posisi duduk yang dekat area event sesuai ketersediaan',
            'Waktu kunjungan lebih panjang untuk menikmati keseluruhan acara',
        ],
        'notes' => [
            'Cocok untuk tamu yang datang saat ada agenda hiburan malam.',
            'Sebaiknya reservasi lebih awal pada akhir pekan.',
            'Ketersediaan spot mengikuti jadwal event di hari yang dipilih.',
        ],
    ],
    'private-event-space' => [
        'slug' => 'private-event-space',
        'aliases' => ['maternity-session'],
        'name' => 'Private Event Space',
        'category' => 'Private Event',
        'price' => 'Mulai Rp. 900.000',
        'duration' => '4 jam',
        'image' => 'assets/images/hero.jpg',
        'summary' => 'Area fleksibel untuk arisan, mini gathering, atau perayaan komunitas.',
        'description' => 'Pilihan reservasi untuk acara yang membutuhkan ruang lebih privat dengan flow tamu yang rapi, tetap santai, dan tetap terasa seperti nongkrong di Cafe Amiko.',
        'facilities' => [
            'Area reservasi untuk 8-12 orang',
            'Pilihan paket minuman dan snack sharing',
            'Set up meja fleksibel sesuai kebutuhan acara',
            'Koordinasi awal dengan tim operasional',
        ],
        'notes' => [
            'Cocok untuk birthday dinner kecil, arisan, atau gathering komunitas.',
            'Perlu konfirmasi detail acara sebelum hari reservasi.',
            'Tambahan kebutuhan dekor atau layout dapat dibicarakan terpisah.',
        ],
    ],
];
